export const migrations = {
  journal: {
    entries: [
      {
        idx: 0,
        when: 1780135301055,
        tag: '0000_new_namor',
        breakpoints: true,
      },
      {
        idx: 1,
        when: 1780221701055,
        tag: '0001_exercise_notes',
        breakpoints: true,
      },
      {
        idx: 2,
        when: 1780308101055,
        tag: '0002_exercise_library',
        breakpoints: true,
      },
      {
        idx: 3,
        when: 1781018447278,
        tag: '0003_typical_skaar',
        breakpoints: true,
      },
    ],
  },
  migrations: {
    m0000: [
      "CREATE TABLE `exercises` (",
      "\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,",
      "\t`name` text NOT NULL",
      ");",
      "--> statement-breakpoint",
      "CREATE UNIQUE INDEX `exercises_name_unique` ON `exercises` (`name`);--> statement-breakpoint",
      "CREATE TABLE `program_days` (",
      "\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,",
      "\t`program_id` integer NOT NULL,",
      "\t`day_index` integer NOT NULL,",
      "\t`name` text NOT NULL,",
      "\tFOREIGN KEY (`program_id`) REFERENCES `programs`(`id`) ON UPDATE no action ON DELETE no action",
      ");",
      "--> statement-breakpoint",
      "CREATE TABLE `program_exercises` (",
      "\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,",
      "\t`program_day_id` integer NOT NULL,",
      "\t`exercise_index` integer NOT NULL,",
      "\t`exercise_id` integer NOT NULL,",
      "\t`targets_json` text NOT NULL,",
      "\tFOREIGN KEY (`program_day_id`) REFERENCES `program_days`(`id`) ON UPDATE no action ON DELETE no action,",
      "\tFOREIGN KEY (`exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE no action",
      ");",
      "--> statement-breakpoint",
      "CREATE TABLE `programs` (",
      "\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,",
      "\t`name` text NOT NULL,",
      "\t`active_day_index` integer DEFAULT 0 NOT NULL",
      ");",
      "--> statement-breakpoint",
      "CREATE TABLE `sessions` (",
      "\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,",
      "\t`date` text NOT NULL,",
      "\t`exercise_id` integer NOT NULL,",
      "\t`sets_json` text NOT NULL,",
      "\t`targets_json` text NOT NULL,",
      "\tFOREIGN KEY (`exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE no action",
      ");",
      "--> statement-breakpoint",
      "CREATE INDEX `idx_sessions_date` ON `sessions` (`date`);--> statement-breakpoint",
      "CREATE INDEX `idx_sessions_exercise` ON `sessions` (`exercise_id`);",
    ].join("\n"),
    m0001: "ALTER TABLE `exercises` ADD `notes` text;",
    m0002: [
      "ALTER TABLE `exercises` ADD `muscle_groups` text;",
      "--> statement-breakpoint",
      "ALTER TABLE `exercises` ADD `equipment` text;",
      "--> statement-breakpoint",
      "ALTER TABLE `exercises` ADD `library_id` text;",
      "--> statement-breakpoint",
      "ALTER TABLE `exercises` ADD `library_confidence` integer;",
    ].join("\n"),
    m0003: [
      "ALTER TABLE `sessions` ADD `source` text DEFAULT 'manual' NOT NULL;--> statement-breakpoint",
      "ALTER TABLE `sessions` ADD `source_id` text;--> statement-breakpoint",
      "CREATE UNIQUE INDEX `idx_sessions_source_id` ON `sessions` (`source`,`source_id`);"
    ].join("\n"),
  },
};
