import { StyleSheet } from 'react-native';
import { C } from '@/components/spuddy/palette';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  centered: { alignItems: 'center', justifyContent: 'center' },
  emptyTitle: { fontSize: 20, fontWeight: '700', color: C.text, marginBottom: 8 },
  emptyText: { fontSize: 15, color: C.sub, textAlign: 'center', lineHeight: 22 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 12,
  },
  backBtn: {
    width: 36, height: 36, borderRadius: 12,
    backgroundColor: C.card,
    alignItems: 'center', justifyContent: 'center',
  },
  backArrow: { fontSize: 18, color: C.text2 },
  headerMid: { flex: 1 },
  headerDay: { fontSize: 17, fontWeight: '700', color: C.text, letterSpacing: -0.3 },
  headerProgress: { fontSize: 12, color: C.sub, marginTop: 1 },
  finishBtnText: { fontSize: 14, fontWeight: '600', color: C.sub },

  strip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 18,
    paddingBottom: 12,
    gap: 8,
  },
  stripChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.card,
    gap: 7,
  },
  stripChipActive: { borderColor: C.hit, backgroundColor: C.hitBg },
  stripChipDone: { borderColor: C.border, backgroundColor: 'transparent', opacity: 0.6 },
  stripChipPressed: { opacity: 0.7 },
  stripChipName: { fontSize: 12, fontWeight: '600', color: C.text2 },
  stripChipNameActive: { color: C.hit },
  stripChipNameDone: { color: C.muted },
  stripDots: { flexDirection: 'row', gap: 4 },
  stripDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: C.border },
  stripDotHit: { backgroundColor: C.hit },
  stripDotMiss: { backgroundColor: C.below },
  stripDotActive: { backgroundColor: 'transparent', borderWidth: 1, borderColor: C.hit },

  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, gap: 20 },

  exBlock: { paddingTop: 8, gap: 4 },
  exName: { fontSize: 22, fontWeight: '700', color: C.text, letterSpacing: -0.4 },

  setCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
  },
  setList: {
    backgroundColor: C.card,
  },
  setListOpen: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  setRowDone: { opacity: 0.7 },
  setRowActive: { backgroundColor: C.surface },
  setRowFuture: { opacity: 0.35 },
  setDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.border, flexShrink: 0 },
  setDotDone: { backgroundColor: C.hit },
  setDotActive: { backgroundColor: 'transparent', borderWidth: 1.5, borderColor: C.hit },
  setRowLabel: { fontSize: 12, color: C.sub, width: 44 },
  setRowLabelActive: { fontSize: 12, fontWeight: '600', color: C.text2, width: 44 },
  setRowLabelFuture: { fontSize: 12, color: C.muted, width: 44 },
  setRowResult: { flex: 1, fontSize: 14, fontWeight: '600', textAlign: 'right' },
  setHit: { color: C.hit },
  setMiss: { color: C.below },
  setRowTarget: { flex: 1, fontSize: 14, fontWeight: '600', color: C.text, textAlign: 'right' },
  setRowFutureVal: { flex: 1, fontSize: 13, color: C.muted, textAlign: 'right' },

  addSetRow: {
    paddingVertical: 11,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    opacity: 0.5,
    borderWidth: 1,
    borderColor: C.muted,
    borderStyle: 'dashed',
  },
  addSetText: { fontSize: 13, fontWeight: '500', color: C.muted },

  bottom: {
    paddingHorizontal: 18,
    paddingTop: 14,
    backgroundColor: C.bg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
    gap: 12,
  },

  stepperRow: { flexDirection: 'row', gap: 0 },
  stepperDivider: { width: 12 },
  stepper: {
    flex: 1, flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 14, borderWidth: 1, borderColor: C.border,
    overflow: 'hidden',
  },
  stepBtn: { width: 48, height: 56, alignItems: 'center', justifyContent: 'center', backgroundColor: C.card2 },
  stepBtnPressed: { backgroundColor: C.cardSoft },
  stepBtnText: { fontSize: 22, color: C.text, fontWeight: '300' },
  stepValue: { flex: 1, alignItems: 'center', gap: 2 },
  stepNum: { fontSize: 22, fontWeight: '700', color: C.text, letterSpacing: -0.5, fontVariant: ['tabular-nums'] },
  stepLabel: { fontSize: 9, color: C.muted, textTransform: 'uppercase', letterSpacing: 1 },

  restBlock: { alignItems: 'center', gap: 8, paddingVertical: 4 },
  restLabel: { fontSize: 11, color: C.muted, textTransform: 'uppercase', letterSpacing: 1 },
  restTime: { fontSize: 48, fontWeight: '700', color: C.text, letterSpacing: -2, fontVariant: ['tabular-nums'] },
  restBar: { width: '100%', height: 3, backgroundColor: C.faint, borderRadius: 2, overflow: 'hidden' },
  restBarFill: { height: '100%', backgroundColor: C.hit, borderRadius: 2 },
  skipBtn: { marginTop: 4, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: C.border },
  skipBtnPressed: { backgroundColor: C.card },
  skipBtnText: { fontSize: 13, fontWeight: '600', color: C.sub },

  confirmBtn: { backgroundColor: C.hit, borderRadius: 14, paddingVertical: 16, alignItems: 'center', justifyContent: 'center' },
  confirmBtnPressed: { opacity: 0.85 },
  confirmBtnText: { fontSize: 16, fontWeight: '700', color: C.bg, letterSpacing: -0.2 },

  noteAddBtn: {
    flexDirection: 'row', alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: 5, paddingHorizontal: 10,
    borderRadius: 8, borderWidth: 1, borderColor: C.border,
  },
  noteAddBtnText: { fontSize: 12, color: C.sub },
  noteBtnFilled: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingVertical: 1 },
  noteBtnText: { flex: 1, fontSize: 13, color: C.sub, lineHeight: 18 },
  noteBtnEdit: {
    paddingVertical: 2, paddingHorizontal: 7,
    borderRadius: 6, borderWidth: 1, borderColor: C.border,
  },
  noteBtnEditText: { fontSize: 11, color: C.muted },

  noteOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
  },
  noteSheet: {
    backgroundColor: C.bg2,
    borderTopWidth: 1, borderTopColor: C.border,
    borderRadius: 24, borderBottomLeftRadius: 0, borderBottomRightRadius: 0,
    padding: 20, paddingBottom: 40,
    gap: 12,
  },
  noteSheetHandle: {
    width: 36, height: 4, borderRadius: 2,
    backgroundColor: C.border, alignSelf: 'center', marginBottom: 4,
  },
  noteSheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  noteSheetTitle: { fontSize: 15, fontWeight: '700', color: C.text },
  noteSheetCancel: { fontSize: 14, fontWeight: '400', color: C.muted },
  noteSheetDone: { fontSize: 14, fontWeight: '600', color: C.hit },
  noteInput: {
    backgroundColor: C.card, borderWidth: 1, borderColor: C.border,
    borderRadius: 12, padding: 12, paddingTop: 12,
    fontSize: 14, color: C.text, lineHeight: 21,
    minHeight: 80, textAlignVertical: 'top',
  },
  noteSheetHint: { fontSize: 12, color: C.muted },
});
